import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Menu from "./_components/Menu/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${font.className}`}>
      <body>
        <Menu />
        {children}
      </body>
    </html>
  );
}
